### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by dogtopus** [github-af/SmartPGP#50]
I noticed that the ownership of this project has been transferred out from the ANSSI GitHub. Could you please elaborate why it's been done this way? Does it have something to do with the perceived relationship between this and ANSSI the organization (which I'd say isn't something very reputable among the privacy-aware folks out there)?

**Comment by github-af** [comment]
I was the main (and only) maintainer of this project when I worked at ANSSI. So when I quitted ANSSI mid-june they agreed to transfer me the ownership of my project.
