### ISSUE TITLE
Setting serial number?

### ISSUE THREAD

**Issue by rpavlik** [github-af/SmartPGP#52]
I can't seem to figure out how to set the serial number or get it to generate one. As such I assume it won't work very well if I have more than one of these cards.  I'm using a J3R180 card, and as long as I manage gpg and pcscd fighting, I can get this output:

```
gpg --card-status
Reader ...........: 04E6:5116:53312211227478:0
Application ID ...: D276000124010304AFAF000000000000
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: unknown
Serial number ....: 00000000
```

I searched the repo but could not find references to card serial number other than in some test scripts. Is this something set with install parameters? custom APDUs? Theoretically generated from some unique on-card value?

I do see that gpg thinks the AID is D276000124010304AFAF000000000000 which ends in a lot of zeroes - do I customize the app AID to set the serial?

I am installing with `gp --load ~/Downloads/SmartPGP-v1.22.2-jc304-rsa_up_to_4096.cap`

**Comment by rpavlik** [comment]
Ahh, sorry for the confusing question. Looks like it is actually in the AID per the OpenPGP card spec, go figure.

Do you have any sample command lines to correctly install the applet with a non-zero serial number?

**Comment by github-af** [comment]
With `gp` and the the released CAP files from SmartPGP, you can load and install SmartPGP with a custom serial number with a single command, e.g. to set the AID (which includes the serial number) of the created instance of the applet to `d276000124010304c0decdf177610000`:
```
gp --load SmartPGP-v1.22.2-jc304-rsa_up_to_4096.cap --package D27600012401 --applet D276000124010304AFAF000000000000 --create d276000124010304c0decdf177610000
```

**Comment by martinpaljak** [comment]
> With `gp` and the released CAP files from SmartPGP, you can load and install SmartPGP with a custom serial number with a single command, e.g. to set the AID (which includes the serial number) of the created instance of the applet to `d276000124010304c0decdf177610000`:
> 
> ```
> gp --load SmartPGP-v1.22.2-jc304-rsa_up_to_4096.cap --package D27600012401 --applet D276000124010304AFAF000000000000 --create d276000124010304c0decdf177610000
> ```

The shorthand which should be:

```
 gp --install SmartPGP-v1.22.2-jc304-rsa_up_to_4096.cap --create d276000124010304c0decdf177610000
```

**Comment by rpavlik** [comment]
Awesome, thanks both of you so much!
